### ISSUE TITLE
Make graphs easier to match to labels

### ISSUE THREAD

**Issue by RByers** [ArthurSonzogni/CommitTracker#11]
I was talking about graphs like this with someone:
![image](https://github.com/user-attachments/assets/84910f00-e7e9-47ab-918b-b7973c3cd65b)

The mentioned that they had a lot of trouble matching the legend to the lines, eg. in this one is the top orange line Microsoft or Arm? It looks to me like the legend is perhaps sorted by total volume, but I see the point. They suggested that hovering should show a label with the org/repo name in addition to the value. I don't know what your graphing library supports, but for screenshotting purposes it might be nice if you could persistently show labels at the right edge.

**Comment by ArthurSonzogni** [comment]
> I don't know what your graphing library supports.

The SVG is built by hand with the help of D3. The possibilities are limitless.

---

I agree, it can be difficult to match the legend to the lines, especially in dense areas of the graph.  The suggestion to show labels on hover is a good one, and persistent labels at the right edge would definitely improve readability for screenshots.

In addition to those ideas, I've been exploring ways to improve the visual clarity of the graph itself. One approach is to use an SVG filter to create a subtle outline or glow around the text, making it stand out from the lines. Here's a concept image:

![image](https://github.com/user-attachments/assets/35869e78-847f-4ddd-a9e0-389b3988df81)

Smoothing the curves could also contribute to a more visually pleasing and less cluttered appearance.

We may also want the legend to update depending on where the cursor is located.

**Comment by RByers** [comment]
Cool, nice! Wow the graphs were so pretty already with their animations that I assumed you used some library. Nice work :-)
